@echo off
mkdir "src\js\JS00_-_UTIL_-_Web-Page_-_Static-Page-Utility-Scripts"
mkdir "src\js\JS01_-_UTIL_-_Web-App_-_Page-Utility-Scripts"
mkdir "src\js\JS02_-_UTIL_-_Web-App_-_Client-Application-Utility-Scripts"
mkdir "src\js\JS03_-_UTIL_-_Web-App_-_Server-Application-Utility-Scripts"
mkdir "src\js\JS04_-_UTIL_-_Web-App_-_Third-Party-Libraries"
mkdir "src\js\JS05_-_UTIL_-_Web-App_-_File-Loading-&-Processing-Scripts"
mkdir "src\js\JS06_-_UTIL_-_Web-App_-_Json-&-Data-Loading-Parsing-&-Processing"
mkdir "src\js\JS07_-_UTIL_-_Web-App_-_State-&-Data-Management-Scripts"
mkdir "src\js\JS08_-_UTIL_-_Web-App_-_UI-&-DOM-Interaction-Scripts"
mkdir "src\js\JS09_-_UTIL_-_Web-App_-_API-&-Data-Integration-Scripts"
mkdir "src\js\JS10_-_FUNC_-_User-Interface-&-DOM-Interaction-Functions"
mkdir "src\js\JS11_-_UTIL_-_Web-App_-_Common-User-InterfaceScripts"
mkdir "src\js\JS12_-_UTIL_-_Web-App_-_DOM-Interaction-Scripts"
mkdir "src\js\JS14_-_UTIL_-_Web-App_-_User-Interaction-Event-Handling-Scripts"
mkdir "src\js\JS20_-_FUNC_-_Rendering-&-Canvas-Specific-Functions"
mkdir "src\js\JS21_-_UTIL_-_Web-App_-_Rendering-Loop-Scripts"
mkdir "src\js\JS22_-_UTIL_-_Web-App_-_Canvas-Setup-Scripts"
mkdir "src\js\JS23_-_UTIL_-_Web-App_-_Animation-&-Transition-Scripts"
mkdir "src\js\JS30_-_UTIL_-_Web-App_-_Security-&-Privacy-Scripts"
mkdir "src\js\JS40_-_UTIL_-_Web-App_-_Error-Handling-&-Debugging-Scripts"
mkdir "src\js\JS41_-_UTIL_-_Web-App_-_Performance-Optimisation-Scripts"
mkdir "src\js\JS50_-_FUNC_-_Global-Utility-Functions"
mkdir "src\js\JS51_-_FUNC_-_Global-Math-Functions"

echo Directory structure created successfully! 